const cuiData = [
  "Abruzzese",
  "Aceh",
  "Aegean",
  "Afghan",
  "Afghani",
  "African",
  "Agritourism",
  "Alentejana",
  "Algerian",
  "Altoatesine",
  "Amazonian",
  "American",
  "Amish",
  "Andhra",
  "Angolan",
  "Apulian",
  "Arabian",
  "Argentine",
  "Armenian",
  "Arunachalese",
  "Asian",
  "Asian Fusion",
  "Assamese",
  "Australian",
  "Austrian",
  "Author",
  "Awadhi",
  "Azerbaijani",
  "Azorean",
  "Bagels",
  "Baiana",
  "Bakery",
  "Bakmi",
  "Bakso",
  "Balinese",
  "Balkans",
  "Balti",
  "Bangka",
  "Bangladeshi",
  "Bánh mì",
  "Basque",
  "Batak",
  "BBQ",
  "Belanda",
  "Belgian",
  "Bengali",
  "Betawi",
  "Bihari",
  "Biryani",
  "Black Sea",
  "Bohri",
  "Börek",
  "Brasserie",
  "Brazilian",
  "Breakfast",
  "British",
  "Bubble Tea",
  "Bulgarian",
  "Bún bò Huế",
  "Burger",
  "Burmese",
  "Cabinet Food",
  "Cafe Food",
  "Cafeteria",
  "Caipira",
  "Cajun",
  "cake",
  "Calabrian",
  "California",
  "Cambodian",
  "Canadian",
  "Cantonese",
  "Cape Malay",
  "Cape Verdean",
  "Capixaba",
  "Caribbean",
  "Carvery",
  "Catalan",
  "Caucasian",
  "Central Anatolia",
  "Central Asian",
  "Charcoal Chicken",
  "Charcoal Grill",
  "Chettinad",
  "Chifa",
  "Chilean",
  "Chili",
  "Chinese",
  "Chinese Muslim",
  "Çiğ Köfte",
  "Coffee",
  "Coffee and Tea",
  "Colombian",
  "Cơm",
  "Contemporary",
  "Continental",
  "Creole",
  "Crepes",
  "Croatian",
  "Cuban",
  "Cucina Campana",
  "Curry",
  "Cypriot",
  "Czech",
  "Danish",
  "Deli",
  "Delight Goodies",
  "Desserts",
  "Dim Sum",
  "Dimsum",
  "Diner",
  "Docerias",
  "Dominican",
  "Döner",
  "Donuts",
  "Dumplings",
  "Durban",
  "Dutch",
  "Eastern Anatolia",
  "Eastern European",
  "Ecuadorian",
  "Egyptian",
  "Emilian",
  "Emirati",
  "Empanadas",
  "Ethiopian",
  "European",
  "Falafel",
  "Fast Food",
  "Fijian",
  "Filipino",
  "Finger Food",
  "First Nations",
  "Fish and Chips",
  "Floribbean",
  "Fondue",
  "Foul",
  "French",
  "Fresh Fish",
  "Fried Chicken",
  "Friulan",
  "Frozen Yogurt",
  "Fujian",
  "Fusion",
  "Garhwali",
  "Gaúcha",
  "Georgian",
  "German",
  "Giblets",
  "Goan",
  "Gourmet Fast Foo",
  "Greek",
  "Grill",
  "Grill House",
  "Grilled Chicken",
  "Grocery",
  "Gujarati",
  "Gulf Food",
  "Guyanese",
  "Hainanese",
  "Hakka Chinese",
  "Haute Cuisine",
  "Hawaiian",
  "Healthy Food",
  "Himachali",
  "Hokkien",
  "Home-made",
  "Hong Kong Style",
  "Hot dogs",
  "Hot Pot",
  "Hunan",
  "Hungarian",
  "Hyderabadi",
  "Ice Cream",
  "Ikan Bakar",
  "Illocano",
  "Indian",
  "Indo-Chinese",
  "Indonesian",
  "International",
  "Iranian",
  "Iraqi",
  "Irish",
  "Israeli",
  "Italian",
  "Izgara",
  "Jamaican",
  "Japanese",
  "Japanese BBQ",
  "Jawa",
  "Jewish",
  "Jiangnan",
  "Juices",
  "Kaak",
  "Kalimantan",
  "Kapampangan",
  "Kashmiri",
  "Kathiyawadi",
  "Kazakh",
  "Kebab",
  "Kebabs",
  "Kerala",
  "Khaleeji",
  "Kiwi",
  "Kokoreç",
  "Konkan",
  "Korean",
  "Korean BBQ",
  "Kumpir",
  "Kyrgyz",
  "Laotian",
  "Latin American",
  "Lebanese",
  "Ligurian",
  "Lithuanian",
  "Lombard",
  "Lombok",
  "Lounge",
  "Lucanian",
  "Lucknowi",
  "Madeiran",
  "Maharashtrian",
  "Makassar",
  "Malatang",
  "Malay",
  "Malaysian",
  "Maltese",
  "Malwani",
  "Manado",
  "Manakish",
  "Mandi",
  "Mangalorean",
  "Manipuri",
  "Martabak",
  "Mauritian",
  "Meat Pie",
  "Medan",
  "Mediterania",
  "Mediterranean",
  "Meghalayan",
  "Mexican",
  "Middle Eastern",
  "Mineira",
  "Minhota",
  "Mishti",
  "Mithai",
  "Mizo",
  "Modern Australia",
  "Modern European",
  "Modern Indian",
  "Modern New Zeala",
  "Moldovan",
  "Molecular",
  "Momos",
  "Mongolian",
  "Moravian",
  "Moroccan",
  "Moroccon",
  "Mozambican",
  "Mughlai",
  "Multi Cuisine",
  "Naga",
  "Native Australia",
  "Neapolitan",
  "Nepalese",
  "New American",
  "New Mexican",
  "New Zealand",
  "Nicaraguan",
  "Nigerian",
  "Nikkei",
  "North Eastern",
  "North Indian",
  "Northern Chinese",
  "Nyonya",
  "Odia",
  "Old Bohemian",
  "Old Turkish Bars",
  "Oriental",
  "Oriya",
  "Others",
  "Ottoman",
  "Paan",
  "Pacific",
  "Pacific Northwest",
  "Padang",
  "Pakistani",
  "Palembang",
  "Pan Asian",
  "Pancake",
  "Panini",
  "Pantanera",
  "Parma",
  "Parsi",
  "Pasta",
  "Pastry",
  "Patisserie",
  "Peranakan",
  "Pernambucana",
  "Persian",
  "Peruvian",
  "Petiscos",
  "Pho",
  "Piadineria",
  "Piedmont",
  "Pilav",
  "Pizza",
  "Po'Boys",
  "Poké",
  "Polish",
  "Portuguese",
  "Poutine",
  "Pub Food",
  "Pub Grub",
  "Puerto Rican",
  "Qatari",
  "Quebecois",
  "Raclette",
  "Rajasthani",
  "Ramen",
  "Relief fund",
  "Restaurant Cafe",
  "Retail Products",
  "Roast",
  "Roast Chicken",
  "Rolls",
  "Roman",
  "Romanian",
  "Russian",
  "Saj",
  "Salad",
  "Salgados",
  "Salvadorean",
  "Sandwich",
  "Santomean",
  "Saoji",
  "Sardinian",
  "Satay",
  "Scandinavian",
  "Scottish",
  "Seafood",
  "Senegalese",
  "Shake",
  "Shanghai",
  "Shawarma",
  "Sichuan",
  "Sicilian",
  "Sikkimese",
  "Sindhi",
  "Singaporean",
  "Slovak",
  "Slovakian",
  "Slovenian",
  "Snack Bar",
  "Snacks",
  "Somali",
  "Soto",
  "Soul Food",
  "South African",
  "South American",
  "South East",
  "South Indian",
  "Southern",
  "Southern American",
  "Southwestern",
  "Spanish",
  "Sri Lankan",
  "Steak",
  "Steamboat",
  "Sula",
  "Sulawesi",
  "Sumatera",
  "Sunda",
  "Sushi",
  "Swedish",
  "Swiss",
  "Syrian",
  "Taco",
  "Taiwanese",
  "Tamil",
  "Tanzanian",
  "Tapas",
  "Tavola Calda",
  "Tavola Fredda",
  "Tea",
  "Tea House",
  "Teochew",
  "Teppanyaki",
  "Teriyaki",
  "Tex-Mex",
  "Thai",
  "Tibetan",
  "Tibetian",
  "Transmontana",
  "Trinbagonian",
  "Tripuri",
  "Tunisian",
  "Turkish",
  "Turkish Pizza",
  "Tuscan",
  "Ukrainian",
  "Uruguayan",
  "Uyghur",
  "Uzbek",
  "Vegan",
  "Vegetarian",
  "Venetian",
  "Venezuelan",
  "Venison",
  "Vietnamese",
  "Waffle",
  "Welsh",
  "West Indian",
  "Western",
  "World Cuisine",
  "Wraps",
  "Xinjiang",
  "Yemeni",
  "Yogyakarta",
  "Yugoslavian",
  "Yum Cha",
  "Yunnan",
  "Zambian",
];

const cuiItems = document.querySelectorAll(".cui-item");






const changeData = (data, items) => {
  items.forEach((element) => {
    element.innerHTML = ""; // Clear the previous content inside .cui-item elements
  });

  if (data.length === 0) {
    // If the filtered data is empty, show a message
    const notFoundMessage = document.createElement("p");
    notFoundMessage.textContent = "Data not found";
    items.forEach((element) => {
      element.appendChild(notFoundMessage.cloneNode(true));
    });
  } else {
    // If there is filtered data, display the items as usual
    data.forEach((item, i) => {
      const card = document.createElement("div");
      card.classList.add("cui_check");

      card.innerHTML = `
        <input type="checkbox" id="${i}" />
        <p>${item}</p>
      `;

      items.forEach((element) => {
        element.appendChild(card.cloneNode(true));
      });
    });
  }
};

// Set the data-search-value attribute for each cui-item element
cuiItems.forEach((item) => {
  item.dataset.searchValue = item.textContent.toLowerCase();
});

// Call the changeData function with the entire cuiData array to show all data by default for both search bars
changeData(cuiData, cuiItems);

// Function to handle search for each search bar
const handleSearch = (searchBar) => {
  searchBar.addEventListener("keyup", (e) => {
    let val = e.target.value.trim(); // Trim whitespace from the input value

    // Filter the cuiData based on the input value
    let newData = cuiData.filter(
      (item) => item.toLowerCase().startsWith(val.toLowerCase())
    );

    // Update the cui-item element with the filtered data or "Data not found" message
    const cuiItem = searchBar.parentElement.nextElementSibling;
    changeData(newData, [cuiItem]);
  });
};

// Search items of cuisines for the first search bar
const searchBar1 = document.querySelector("#cui-box"); // Use the unique ID for the first search bar
handleSearch(searchBar1);

// Search items of cuisines for the second search bar
const searchBar2 = document.querySelector("#cui-box-2"); // Use the unique ID for the second search bar
handleSearch(searchBar2);
